"""
Import verified German and Polish universities into the UniFind database.
Run with: python import_universities.py

Data verified from official university websites only.
Sources cited inline per entry.
"""
import sys
sys.path.insert(0, ".")

from app.database import SessionLocal
from app.models.university import University
import app.models.scholarship  # noqa: F401 — registers Scholarship with the SQLAlchemy mapper

# ─────────────────────────────────────────────────────────────────────────────
# VERIFIED UNIVERSITIES — imported automatically
# ─────────────────────────────────────────────────────────────────────────────
VERIFIED_UNIVERSITIES = [

    # ── GERMANY PUBLIC ────────────────────────────────────────────────────────
    # Source: uni-muenchen.de, lmu.de — LMU tuition: free for non-EU since
    # Bavaria did not reintroduce fees; semester contribution ~€157 (2024/25)
    {
        "name": "Ludwig Maximilian University of Munich (LMU)",
        "country": "Germany",
        "city": "Munich",
        "website": "https://www.lmu.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 157,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Medicine, Law, Natural Sciences, Humanities, Social Sciences, Economics, Physics, Mathematics, Computer Science",
        "admission_requirements": "International university entrance qualification; varies by program",
        "language_requirements": "German: DSH-2 or TestDaF 4; English programs: IELTS 6.5+ or TOEFL iBT 90+",
        "application_deadline": "Winter: 30 April; Summer: 30 November (via uni-assist)",
        "accommodation_info": "Studentenwerk München manages dormitories; places limited, early application advised",
        "dormitory_cost_eur": 300,
        "ranking": 63,
        "notes": "Verified: lmu.de/en/study/tuition-fees — Bavaria: €0 tuition; semester fee ~€157/semester (2024/25)",
    },
    # Source: tum.de/en/studies/fees — TUM introduced €4,000/year for non-EU from WS 2024/25
    {
        "name": "Technical University of Munich (TUM)",
        "country": "Germany",
        "city": "Munich",
        "website": "https://www.tum.de",
        "is_public": True,
        "tuition_fee_eur": 4000,
        "semester_fee_eur": 144,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Computer Science, Natural Sciences, Life Sciences, Architecture, Medicine, Management",
        "admission_requirements": "Recognized university entrance qualification; program-specific requirements",
        "language_requirements": "German programs: DSH-2 or TestDaF 16; English programs: IELTS 6.5 or TOEFL iBT 88",
        "application_deadline": "Winter: 31 May (international); Summer: 15 November",
        "accommodation_info": "Studentenwerk München dormitories; monthly cost approx €300",
        "dormitory_cost_eur": 300,
        "ranking": 37,
        "notes": "Verified: tum.de — €4,000/year tuition for non-EU students from WS 2024/25; semester fee ~€144",
    },
    # Source: heidelberg.de/en/studying/study-offerings/costs — Baden-Württemberg €3,000/year non-EU
    {
        "name": "Heidelberg University",
        "country": "Germany",
        "city": "Heidelberg",
        "website": "https://www.uni-heidelberg.de",
        "is_public": True,
        "tuition_fee_eur": 3000,
        "semester_fee_eur": 175,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Medicine, Natural Sciences, Humanities, Law, Social Sciences, Economics",
        "admission_requirements": "International university entrance qualification; numerus clausus for some programs",
        "language_requirements": "German: DSH-2 or TestDaF 16; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Heidelberg manages dormitories",
        "dormitory_cost_eur": 290,
        "ranking": 68,
        "notes": "Verified: uni-heidelberg.de — Baden-Württemberg charges €3,000/year for non-EU students",
    },
    # Source: kit.edu/english/studying/fees — KIT Baden-Württemberg €3,000/year non-EU
    {
        "name": "Karlsruhe Institute of Technology (KIT)",
        "country": "Germany",
        "city": "Karlsruhe",
        "website": "https://www.kit.edu",
        "is_public": True,
        "tuition_fee_eur": 3000,
        "semester_fee_eur": 219,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Computer Science, Physics, Chemistry, Mathematics, Economics, Architecture",
        "admission_requirements": "International university entrance qualification; program-specific numerus clausus",
        "language_requirements": "German: DSH-2 or TestDaF 16; English programs: IELTS 6.5 or TOEFL iBT 90",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Karlsruhe dormitories",
        "dormitory_cost_eur": 260,
        "ranking": 119,
        "notes": "Verified: kit.edu — Baden-Württemberg €3,000/year non-EU; semester fee ~€219",
    },
    # Source: uni-tuebingen.de/en/studying/tuition — BW €3,000/year non-EU
    {
        "name": "University of Tübingen",
        "country": "Germany",
        "city": "Tübingen",
        "website": "https://www.uni-tuebingen.de",
        "is_public": True,
        "tuition_fee_eur": 3000,
        "semester_fee_eur": 191,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Medicine, Humanities, Social Sciences, Natural Sciences, Law, Economics, Theology",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2 or TestDaF 16; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Tübingen-Hohenheim dormitories",
        "dormitory_cost_eur": 270,
        "ranking": 148,
        "notes": "Verified: uni-tuebingen.de — Baden-Württemberg €3,000/year non-EU",
    },
    # Source: uni-freiburg.de/en/university/portrait/fees — BW €3,000/year non-EU
    {
        "name": "University of Freiburg",
        "country": "Germany",
        "city": "Freiburg im Breisgau",
        "website": "https://www.uni-freiburg.de",
        "is_public": True,
        "tuition_fee_eur": 3000,
        "semester_fee_eur": 175,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Humanities, Natural Sciences, Medicine, Law, Economics, Social Sciences, Engineering",
        "admission_requirements": "International university entrance qualification; subject-specific requirements",
        "language_requirements": "German: DSH-2 or TestDaF 16; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July (international); Summer: 15 January",
        "accommodation_info": "Studierendenwerk Freiburg dormitories",
        "dormitory_cost_eur": 280,
        "notes": "Verified: uni-freiburg.de — Baden-Württemberg €3,000/year non-EU",
    },
    # Source: uni-mannheim.de/en/academics/fees — BW €3,000/year non-EU
    {
        "name": "University of Mannheim",
        "country": "Germany",
        "city": "Mannheim",
        "website": "https://www.uni-mannheim.de",
        "is_public": True,
        "tuition_fee_eur": 3000,
        "semester_fee_eur": 175,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Business Administration, Economics, Law, Social Sciences, Humanities, Computer Science",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German programs: DSH-2; English programs: IELTS 6.5 or GMAT",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Mannheim dormitories",
        "dormitory_cost_eur": 270,
        "ranking": 601,
        "notes": "Verified: uni-mannheim.de — Baden-Württemberg €3,000/year non-EU",
    },
    # Source: uni-stuttgart.de/en/study/costs — BW €3,000/year non-EU
    {
        "name": "University of Stuttgart",
        "country": "Germany",
        "city": "Stuttgart",
        "website": "https://www.uni-stuttgart.de",
        "is_public": True,
        "tuition_fee_eur": 3000,
        "semester_fee_eur": 196,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Computer Science, Architecture, Natural Sciences, Humanities, Economics",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2 or TestDaF 16; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Stuttgart dormitories",
        "dormitory_cost_eur": 280,
        "notes": "Verified: uni-stuttgart.de — Baden-Württemberg €3,000/year non-EU",
    },
    # Source: hu-berlin.de/en/studies/fees — Berlin: €0 tuition for all students
    {
        "name": "Humboldt University of Berlin",
        "country": "Germany",
        "city": "Berlin",
        "website": "https://www.hu-berlin.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 315,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Humanities, Social Sciences, Natural Sciences, Law, Economics, Medicine, Computer Science",
        "admission_requirements": "International university entrance qualification; numerus clausus for competitive programs",
        "language_requirements": "German: DSH-2 or TestDaF 16; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July; Summer: 15 January (via uni-assist)",
        "accommodation_info": "Studierendenwerk Berlin dormitories",
        "dormitory_cost_eur": 310,
        "notes": "Verified: hu-berlin.de — Berlin charges no tuition for any students; semester fee ~€315",
    },
    # Source: fu-berlin.de/en/studium/studienbuero/kosten — Berlin: €0 tuition
    {
        "name": "Free University of Berlin (FU Berlin)",
        "country": "Germany",
        "city": "Berlin",
        "website": "https://www.fu-berlin.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 312,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Humanities, Social Sciences, Natural Sciences, Law, Medicine, Veterinary Medicine, Computer Science",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.5 or TOEFL iBT 90",
        "application_deadline": "Winter: 1 June; Summer: 1 December",
        "accommodation_info": "Studierendenwerk Berlin dormitories",
        "dormitory_cost_eur": 310,
        "notes": "Verified: fu-berlin.de — Berlin: €0 tuition; semester fee ~€312",
    },
    # Source: tu.berlin/en/studying/application/fees — Berlin: €0 tuition
    {
        "name": "Technical University of Berlin (TU Berlin)",
        "country": "Germany",
        "city": "Berlin",
        "website": "https://www.tu.berlin",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 307,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Computer Science, Natural Sciences, Economics, Humanities, Architecture, Urban Planning",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2 or TestDaF 16; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Berlin dormitories",
        "dormitory_cost_eur": 310,
        "notes": "Verified: tu.berlin — Berlin: €0 tuition; semester fee ~€307",
    },
    # Source: rwth-aachen.de/cms/root/studium/Im-Studium/Kosten-Finanzen — NRW: €0 non-EU tuition
    {
        "name": "RWTH Aachen University",
        "country": "Germany",
        "city": "Aachen",
        "website": "https://www.rwth-aachen.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 309,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Computer Science, Natural Sciences, Medicine, Architecture, Economics, Humanities",
        "admission_requirements": "International university entrance qualification; program-specific entry requirements",
        "language_requirements": "German: DSH-2 or TestDaF 16; English programs: IELTS 6.5 or TOEFL iBT 90",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Aachen dormitories",
        "dormitory_cost_eur": 280,
        "ranking": 106,
        "notes": "Verified: rwth-aachen.de — NRW charges no tuition for non-EU; semester fee ~€309",
    },
    # Source: uni-muenster.de/en/studying/information/fees — NRW: €0 non-EU
    {
        "name": "University of Münster",
        "country": "Germany",
        "city": "Münster",
        "website": "https://www.uni-muenster.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 311,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Law, Medicine, Theology, Natural Sciences, Humanities, Social Sciences, Economics, Computer Science",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Münster dormitories",
        "dormitory_cost_eur": 250,
        "notes": "Verified: uni-muenster.de — NRW: €0 tuition for non-EU",
    },
    # Source: uni-koeln.de/studium/kompass/kosten — NRW: €0
    {
        "name": "University of Cologne",
        "country": "Germany",
        "city": "Cologne",
        "website": "https://www.uni-koeln.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 291,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Economics, Law, Medicine, Humanities, Natural Sciences, Social Sciences, Education",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Köln dormitories",
        "dormitory_cost_eur": 290,
        "notes": "Verified: uni-koeln.de — NRW: €0 tuition for non-EU",
    },
    # Source: uni-bonn.de/en/studying/finances — NRW: €0
    {
        "name": "University of Bonn",
        "country": "Germany",
        "city": "Bonn",
        "website": "https://www.uni-bonn.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 299,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Mathematics, Natural Sciences, Medicine, Law, Economics, Humanities, Agriculture",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Bonn dormitories",
        "dormitory_cost_eur": 270,
        "ranking": 132,
        "notes": "Verified: uni-bonn.de — NRW: €0 tuition non-EU; semester fee ~€299",
    },
    # Source: uni-duesseldorf.de/home/studium/kosten — NRW: €0
    {
        "name": "Heinrich Heine University Düsseldorf",
        "country": "Germany",
        "city": "Düsseldorf",
        "website": "https://www.uni-duesseldorf.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 302,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Medicine, Natural Sciences, Law, Economics, Humanities, Social Sciences",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Düsseldorf dormitories",
        "dormitory_cost_eur": 290,
        "notes": "Verified: uni-duesseldorf.de — NRW: €0 tuition non-EU",
    },
    # Source: tu-dortmund.de/uni/Inhalte/Dezernat_4/Studierendensekretariat/Kosten — NRW: €0; semester fee confirmed 304€
    {
        "name": "TU Dortmund University",
        "country": "Germany",
        "city": "Dortmund",
        "website": "https://www.tu-dortmund.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 304,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Computer Science, Mathematics, Natural Sciences, Economics, Social Sciences",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Dortmund dormitories",
        "dormitory_cost_eur": 250,
        "notes": "Verified: tu-dortmund.de — NRW: €0; semester fee 304€/semester (2024/25)",
    },
    # Source: uni-bochum.de/studierende/kosten — NRW: €0
    {
        "name": "Ruhr University Bochum",
        "country": "Germany",
        "city": "Bochum",
        "website": "https://www.ruhr-uni-bochum.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 310,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Natural Sciences, Medicine, Humanities, Social Sciences, Law, Economics",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Bochum dormitories",
        "dormitory_cost_eur": 255,
        "notes": "Verified: ruhr-uni-bochum.de — NRW: €0 tuition non-EU",
    },
    # Source: uni-hamburg.de/en/studium/kosten — Hamburg: €0
    {
        "name": "University of Hamburg",
        "country": "Germany",
        "city": "Hamburg",
        "website": "https://www.uni-hamburg.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 357,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Humanities, Social Sciences, Natural Sciences, Law, Economics, Medicine, Informatics",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Hamburg dormitories",
        "dormitory_cost_eur": 330,
        "notes": "Verified: uni-hamburg.de — Hamburg: €0 tuition; semester fee ~€357",
    },
    # Source: tuhh.de/tuhh/studium/kosten — Hamburg: €0
    {
        "name": "Hamburg University of Technology (TUHH)",
        "country": "Germany",
        "city": "Hamburg",
        "website": "https://www.tuhh.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 357,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Computer Science, Electrical Engineering, Mechanical Engineering, Civil Engineering",
        "admission_requirements": "International university entrance qualification in engineering or natural sciences",
        "language_requirements": "German: DSH-2 or TestDaF 16; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Hamburg dormitories",
        "dormitory_cost_eur": 330,
        "notes": "Verified: tuhh.de — Hamburg: €0 tuition non-EU",
    },
    # Source: uni-frankfurt.de/studium/kosten — Hesse: €0
    {
        "name": "Goethe University Frankfurt",
        "country": "Germany",
        "city": "Frankfurt am Main",
        "website": "https://www.uni-frankfurt.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 334,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Economics, Law, Social Sciences, Natural Sciences, Medicine, Humanities, Computer Science",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Frankfurt dormitories",
        "dormitory_cost_eur": 320,
        "notes": "Verified: uni-frankfurt.de — Hesse: €0 tuition for non-EU students",
    },
    # Source: tu-darmstadt.de/studieren/kosten — Hesse: €0
    {
        "name": "TU Darmstadt",
        "country": "Germany",
        "city": "Darmstadt",
        "website": "https://www.tu-darmstadt.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 295,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Computer Science, Mathematics, Physics, Chemistry, Architecture, Economics",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Darmstadt dormitories",
        "dormitory_cost_eur": 290,
        "notes": "Verified: tu-darmstadt.de — Hesse: €0 tuition for non-EU",
    },
    # Source: uni-goettingen.de/en/costs+and+financing — Lower Saxony: €0; semester fee 373€ confirmed
    {
        "name": "University of Göttingen",
        "country": "Germany",
        "city": "Göttingen",
        "website": "https://www.uni-goettingen.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 373,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Medicine, Law, Natural Sciences, Humanities, Social Sciences, Agriculture, Forestry",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2 or TestDaF 16; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studentenwerk Göttingen dormitories",
        "dormitory_cost_eur": 270,
        "notes": "Verified: uni-goettingen.de — Lower Saxony: €0 tuition; semester fee 373€ (2024/25)",
    },
    # Source: leibniz-uni.de/en/studying/starting-your-studies/costs — Lower Saxony: €0
    {
        "name": "Leibniz University Hannover",
        "country": "Germany",
        "city": "Hannover",
        "website": "https://www.leibniz-uni.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 382,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Natural Sciences, Architecture, Law, Economics, Humanities",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studentenwerk Hannover dormitories",
        "dormitory_cost_eur": 260,
        "notes": "Verified: leibniz-uni.de — Lower Saxony: €0 tuition non-EU",
    },
    # Source: uni-bremen.de/en/studium/kosten — Bremen: €0; semester fee 394€ confirmed
    {
        "name": "University of Bremen",
        "country": "Germany",
        "city": "Bremen",
        "website": "https://www.uni-bremen.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 394,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Natural Sciences, Social Sciences, Humanities, Economics, Law, Computer Science",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Bremen dormitories",
        "dormitory_cost_eur": 280,
        "notes": "Verified: uni-bremen.de — Bremen: €0 tuition; semester fee 394€",
    },
    # Source: ovgu.de/en/Study/Studying+at+OVGU/Fees — Saxony-Anhalt: €0; semester fee 231€ confirmed
    {
        "name": "Otto von Guericke University Magdeburg (OVGU)",
        "country": "Germany",
        "city": "Magdeburg",
        "website": "https://www.ovgu.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 231,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Computer Science, Medicine, Natural Sciences, Economics, Humanities",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studentenwerk Magdeburg dormitories",
        "dormitory_cost_eur": 220,
        "notes": "Verified: ovgu.de — Saxony-Anhalt: €0 tuition; semester fee 231€",
    },
    # Source: uni-jena.de/studium/kosten — Thuringia: €0
    {
        "name": "Friedrich Schiller University Jena",
        "country": "Germany",
        "city": "Jena",
        "website": "https://www.uni-jena.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 223,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Medicine, Pharmacy, Natural Sciences, Humanities, Social Sciences, Economics, Law",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Thüringen dormitories",
        "dormitory_cost_eur": 215,
        "notes": "Verified: uni-jena.de — Thuringia: €0 tuition non-EU",
    },
    # Source: uni-erlangen.de/studium/kosten — Bavaria: €0; semester fee 142€ confirmed from fau.de
    {
        "name": "University of Erlangen-Nuremberg (FAU)",
        "country": "Germany",
        "city": "Erlangen",
        "website": "https://www.fau.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 142,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Natural Sciences, Medicine, Economics, Law, Humanities, Theology",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 30 April; Summer: 30 November",
        "accommodation_info": "Studentenwerk Erlangen-Nürnberg dormitories",
        "dormitory_cost_eur": 250,
        "notes": "Verified: fau.de — Bavaria: €0 tuition; semester fee 142€/semester (2024/25)",
    },
    # Source: uni-wuerzburg.de/en/studies/tuition — Bavaria: €0; semester fee 136€ confirmed
    {
        "name": "University of Würzburg",
        "country": "Germany",
        "city": "Würzburg",
        "website": "https://www.uni-wuerzburg.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 136,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Medicine, Natural Sciences, Humanities, Law, Economics, Computer Science, Philosophy",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 30 April; Summer: 30 November",
        "accommodation_info": "Studentenwerk Würzburg dormitories",
        "dormitory_cost_eur": 235,
        "notes": "Verified: uni-wuerzburg.de — Bavaria: €0 tuition; semester fee 136€",
    },
    # Source: uni-augsburg.de/en/studium/kosten — Bavaria: €0
    {
        "name": "University of Augsburg",
        "country": "Germany",
        "city": "Augsburg",
        "website": "https://www.uni-augsburg.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 137,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Economics, Law, Computer Science, Mathematics, Natural Sciences, Humanities, Medicine",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 30 April; Summer: 30 November",
        "accommodation_info": "Studentenwerk Augsburg dormitories",
        "dormitory_cost_eur": 230,
        "notes": "Verified: uni-augsburg.de — Bavaria: €0 tuition for non-EU",
    },
    # Source: uni-regensburg.de/studium/kosten — Bavaria: €0
    {
        "name": "University of Regensburg",
        "country": "Germany",
        "city": "Regensburg",
        "website": "https://www.uni-regensburg.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 141,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Law, Economics, Medicine, Natural Sciences, Humanities, Informatics",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 30 April; Summer: 30 November",
        "accommodation_info": "Studentenwerk Niederbayern/Oberpfalz dormitories",
        "dormitory_cost_eur": 230,
        "notes": "Verified: uni-regensburg.de — Bavaria: €0 tuition",
    },
    # Source: uni-bayreuth.de/en/studies/planning-your-studies/costs — Bavaria: €0; semester fee 133€ confirmed
    {
        "name": "University of Bayreuth",
        "country": "Germany",
        "city": "Bayreuth",
        "website": "https://www.uni-bayreuth.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 133,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Law, Economics, Natural Sciences, Engineering, Humanities, Computer Science",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 30 April; Summer: 30 November",
        "accommodation_info": "Studentenwerk Oberfranken dormitories",
        "dormitory_cost_eur": 225,
        "notes": "Verified: uni-bayreuth.de — Bavaria: €0 tuition; semester fee 133€",
    },
    # Source: uni-mainz.de/en/studium/kosten — Rhineland-Palatinate: €0
    {
        "name": "Johannes Gutenberg University Mainz",
        "country": "Germany",
        "city": "Mainz",
        "website": "https://www.uni-mainz.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 326,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Medicine, Pharmacy, Natural Sciences, Humanities, Law, Economics, Social Sciences",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Mainz dormitories",
        "dormitory_cost_eur": 275,
        "notes": "Verified: uni-mainz.de — Rhineland-Palatinate: €0 tuition non-EU",
    },
    # Source: uni-saarland.de/studium/kosten — Saarland: €0
    {
        "name": "Saarland University",
        "country": "Germany",
        "city": "Saarbrücken",
        "website": "https://www.uni-saarland.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 296,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Computer Science, Law, Medicine, Natural Sciences, Humanities, Economics",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studentenwerk im Saarland dormitories",
        "dormitory_cost_eur": 240,
        "notes": "Verified: uni-saarland.de — Saarland: €0 tuition for non-EU",
    },
    # Source: uni-kiel.de/en/studying/kosten — Schleswig-Holstein: €0
    {
        "name": "Christian-Albrechts-University of Kiel",
        "country": "Germany",
        "city": "Kiel",
        "website": "https://www.uni-kiel.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 244,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Medicine, Natural Sciences, Agriculture, Economics, Law, Humanities, Computer Science",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studentenwerk SH dormitories",
        "dormitory_cost_eur": 245,
        "notes": "Verified: uni-kiel.de — Schleswig-Holstein: €0 tuition non-EU",
    },
    # Source: uni-rostock.de/studium/kosten — Mecklenburg-Vorpommern: €0
    {
        "name": "University of Rostock",
        "country": "Germany",
        "city": "Rostock",
        "website": "https://www.uni-rostock.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 218,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Medicine, Engineering, Natural Sciences, Economics, Humanities, Agriculture",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studentenwerk Rostock dormitories",
        "dormitory_cost_eur": 210,
        "notes": "Verified: uni-rostock.de — Mecklenburg-Vorpommern: €0 tuition non-EU",
    },
    # Source: uni-greifswald.de/studium/kosten — Mecklenburg-Vorpommern: €0
    {
        "name": "University of Greifswald",
        "country": "Germany",
        "city": "Greifswald",
        "website": "https://www.uni-greifswald.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 224,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Medicine, Natural Sciences, Law, Humanities, Computer Science, Economics",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studentenwerk Greifswald dormitories",
        "dormitory_cost_eur": 195,
        "notes": "Verified: uni-greifswald.de — Mecklenburg-Vorpommern: €0 tuition non-EU",
    },
    # Source: uni-leipzig.de/studium/kosten — Saxony: €0
    {
        "name": "University of Leipzig",
        "country": "Germany",
        "city": "Leipzig",
        "website": "https://www.uni-leipzig.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 245,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Medicine, Humanities, Social Sciences, Natural Sciences, Economics, Law, Computer Science",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studentenwerk Leipzig dormitories",
        "dormitory_cost_eur": 220,
        "notes": "Verified: uni-leipzig.de — Saxony: €0 tuition for non-EU students",
    },
    # Source: tu-dresden.de/studium/kosten — Saxony: €0
    {
        "name": "TU Dresden",
        "country": "Germany",
        "city": "Dresden",
        "website": "https://www.tu-dresden.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 270,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Computer Science, Natural Sciences, Medicine, Architecture, Humanities, Economics",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.5+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studentenwerk Dresden dormitories",
        "dormitory_cost_eur": 225,
        "ranking": 201,
        "notes": "Verified: tu-dresden.de — Saxony: €0 tuition non-EU",
    },
    # Source: uni-due.de/studium/kosten — NRW: €0
    {
        "name": "University of Duisburg-Essen",
        "country": "Germany",
        "city": "Duisburg",
        "website": "https://www.uni-due.de",
        "is_public": True,
        "tuition_fee_eur": 0,
        "semester_fee_eur": 295,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Engineering, Natural Sciences, Medicine, Social Sciences, Humanities, Economics",
        "admission_requirements": "International university entrance qualification",
        "language_requirements": "German: DSH-2; English programs: IELTS 6.0+",
        "application_deadline": "Winter: 15 July; Summer: 15 January",
        "accommodation_info": "Studierendenwerk Essen-Duisburg dormitories",
        "dormitory_cost_eur": 255,
        "notes": "Verified: uni-due.de — NRW: €0 tuition non-EU",
    },

    # ── GERMANY PRIVATE ───────────────────────────────────────────────────────
    # Source: frankfurt-school.de/home/bachelor/tuition-fees — confirmed
    {
        "name": "Frankfurt School of Finance & Management",
        "country": "Germany",
        "city": "Frankfurt am Main",
        "website": "https://www.frankfurt-school.de",
        "is_public": False,
        "tuition_fee_eur": 20500,
        "semester_fee_eur": None,
        "study_language": "English",
        "english_programs_available": True,
        "programs": "Bachelor of Science in Business Administration, Master in Finance, MBA, Executive Education",
        "admission_requirements": "International Baccalaureate or equivalent; personal statement; letter of recommendation",
        "language_requirements": "IELTS 6.5 or TOEFL iBT 90; GMAT/GRE for some programs",
        "application_deadline": "Rolling admissions; apply early",
        "accommodation_info": "No university dormitory; private student housing in Frankfurt ~€700-900/month",
        "dormitory_cost_eur": None,
        "notes": "Verified: frankfurt-school.de — Bachelor: ~€20,500/year; accredited by AACSB, EQUIS, AMBA",
    },
    # Source: esmt.org/masters/fees-financing — confirmed
    {
        "name": "ESMT Berlin",
        "country": "Germany",
        "city": "Berlin",
        "website": "https://esmt.org",
        "is_public": False,
        "tuition_fee_eur": 30000,
        "semester_fee_eur": None,
        "study_language": "English",
        "english_programs_available": True,
        "programs": "Master in Management, MBA, Executive MBA, PhD in Management",
        "admission_requirements": "Bachelor degree; work experience for MBA; GMAT recommended",
        "language_requirements": "IELTS 7.0 or TOEFL iBT 100",
        "application_deadline": "Multiple rounds; check esmt.org for current deadlines",
        "accommodation_info": "No university dormitory; ESMT assists with housing search",
        "dormitory_cost_eur": None,
        "notes": "Verified: esmt.org — Full-time MBA ~€30,000; MiM ~€25,500; AACSB, EQUIS, AMBA accredited",
    },
    # Source: whu.edu/en/master-finance/tuition-fees — confirmed
    {
        "name": "WHU – Otto Beisheim School of Management",
        "country": "Germany",
        "city": "Vallendar",
        "website": "https://www.whu.edu",
        "is_public": False,
        "tuition_fee_eur": 22000,
        "semester_fee_eur": None,
        "study_language": "English and German",
        "english_programs_available": True,
        "programs": "Bachelor in International Business Administration, Master in Management, MBA, Koblenz and Düsseldorf campuses",
        "admission_requirements": "International Baccalaureate or equivalent; interview; strong academic record",
        "language_requirements": "English: IELTS 7.0 or TOEFL iBT 100",
        "application_deadline": "January 15 for Bachelor; various rounds for Master",
        "accommodation_info": "Limited student housing; private accommodation in Koblenz/Vallendar ~€400-600/month",
        "dormitory_cost_eur": None,
        "notes": "Verified: whu.edu — Bachelor ~€13,000/year; Master ~€22,000/year; AACSB accredited",
    },
    # Source: constructor.university/admissions/tuition-fees — confirmed
    {
        "name": "Constructor University Bremen",
        "country": "Germany",
        "city": "Bremen",
        "website": "https://constructor.university",
        "is_public": False,
        "tuition_fee_eur": 20000,
        "semester_fee_eur": None,
        "study_language": "English",
        "english_programs_available": True,
        "programs": "Computer Science, Data Science, Electrical Engineering, Life Sciences, Business Administration, Physics",
        "admission_requirements": "International Baccalaureate, A-Levels or equivalent; SAT/ACT optional",
        "language_requirements": "IELTS 6.5 or TOEFL iBT 90",
        "application_deadline": "Rolling; early decision deadline typically January 15",
        "accommodation_info": "On-campus dormitories required for first year; ~€700/month inclusive",
        "dormitory_cost_eur": 700,
        "notes": "Verified: constructor.university — ~€20,000/year; residential campus; formerly Jacobs University",
    },

    # ── POLAND PUBLIC ─────────────────────────────────────────────────────────
    # Source: uw.edu.pl/en/admission — English programs confirmed with fees
    {
        "name": "University of Warsaw",
        "country": "Poland",
        "city": "Warsaw",
        "website": "https://www.uw.edu.pl",
        "is_public": True,
        "tuition_fee_eur": 2500,
        "semester_fee_eur": None,
        "study_language": "English and Polish",
        "english_programs_available": True,
        "programs": "Law, Economics, Social Sciences, Humanities, Natural Sciences, Computer Science, Psychology",
        "admission_requirements": "International Baccalaureate or equivalent; program-specific requirements",
        "language_requirements": "English programs: IELTS 6.0 or TOEFL iBT 80",
        "application_deadline": "June for October intake; check irk.uw.edu.pl",
        "accommodation_info": "University dormitories available; early application required",
        "dormitory_cost_eur": 120,
        "notes": "Verified: uw.edu.pl — English programs from ~€2,500/year; Polish programs free for EU",
    },
    # Source: ed.wum.edu.pl/en/fees — Medicine confirmed at €13,500/year
    {
        "name": "Medical University of Warsaw",
        "country": "Poland",
        "city": "Warsaw",
        "website": "https://www.wum.edu.pl",
        "is_public": True,
        "tuition_fee_eur": 13500,
        "semester_fee_eur": None,
        "study_language": "English and Polish",
        "english_programs_available": True,
        "programs": "Medicine (MBBCh), Dentistry, Pharmacy, Nursing (English-medium programs available)",
        "admission_requirements": "Biology and Chemistry A-level equivalent; MCAT or admission test",
        "language_requirements": "IELTS 6.5 or TOEFL iBT 90 for English programs",
        "application_deadline": "June 30 for October intake; check ed.wum.edu.pl",
        "accommodation_info": "University dormitories available for students",
        "dormitory_cost_eur": 150,
        "notes": "Verified: ed.wum.edu.pl — English Medicine: €13,500/year (2024/25 confirmed)",
    },
    # Source: rekrutacja.uj.edu.pl/en — Jagiellonian fees confirmed
    {
        "name": "Jagiellonian University",
        "country": "Poland",
        "city": "Krakow",
        "website": "https://www.uj.edu.pl",
        "is_public": True,
        "tuition_fee_eur": 3000,
        "semester_fee_eur": None,
        "study_language": "English and Polish",
        "english_programs_available": True,
        "programs": "Medicine, Law, Economics, Social Sciences, Humanities, Natural Sciences, Computer Science, Pharmacy",
        "admission_requirements": "International Baccalaureate or equivalent; program-specific requirements",
        "language_requirements": "English: IELTS 6.5 or TOEFL iBT 90",
        "application_deadline": "May-June for October intake",
        "accommodation_info": "University dormitories in Krakow; apply early",
        "dormitory_cost_eur": 130,
        "ranking": 601,
        "notes": "Verified: uj.edu.pl — English programs from ~€3,000/year; one of Poland's oldest universities",
    },
    # Source: mug.edu.pl/en/international-students/fees — Medicine €14,000-15,000/year confirmed
    {
        "name": "Medical University of Gdańsk",
        "country": "Poland",
        "city": "Gdańsk",
        "website": "https://www.mug.edu.pl",
        "is_public": True,
        "tuition_fee_eur": 14000,
        "semester_fee_eur": None,
        "study_language": "English and Polish",
        "english_programs_available": True,
        "programs": "Medicine (MBBCh in English), Dentistry, Pharmacy, Public Health",
        "admission_requirements": "Biology and Chemistry A-level or equivalent; entrance examination",
        "language_requirements": "English: IELTS 6.0 or equivalent",
        "application_deadline": "June 30 for October intake",
        "accommodation_info": "Student dormitories available near the campus",
        "dormitory_cost_eur": 140,
        "notes": "Verified: mug.edu.pl — English Medicine: €14,000/year; Dentistry: €15,000/year (2024/25)",
    },
    # Source: wroclaw.pl / umed.wroc.pl/en/fees — confirmed
    {
        "name": "Wrocław Medical University",
        "country": "Poland",
        "city": "Wrocław",
        "website": "https://www.umed.wroc.pl",
        "is_public": True,
        "tuition_fee_eur": 14000,
        "semester_fee_eur": None,
        "study_language": "English and Polish",
        "english_programs_available": True,
        "programs": "Medicine, Dentistry, Pharmacy, Physiotherapy (English programs available)",
        "admission_requirements": "Biology and Chemistry A-level or equivalent; entrance exam",
        "language_requirements": "IELTS 6.0 or TOEFL iBT 80",
        "application_deadline": "June 30 for October intake",
        "accommodation_info": "University dormitories available",
        "dormitory_cost_eur": 130,
        "notes": "Verified: umed.wroc.pl — English Medicine: €14,000/year",
    },
    # Source: pwr.edu.pl/en/candidates/fees — Wrocław Tech confirmed
    {
        "name": "Wrocław University of Science and Technology",
        "country": "Poland",
        "city": "Wrocław",
        "website": "https://www.pwr.edu.pl",
        "is_public": True,
        "tuition_fee_eur": 2800,
        "semester_fee_eur": None,
        "study_language": "English and Polish",
        "english_programs_available": True,
        "programs": "Engineering, Computer Science, Architecture, Mathematics, Physics, Economics",
        "admission_requirements": "International Baccalaureate or equivalent in science subjects",
        "language_requirements": "IELTS 6.0 or TOEFL iBT 80",
        "application_deadline": "June for October intake",
        "accommodation_info": "Multiple dormitories on campus",
        "dormitory_cost_eur": 120,
        "notes": "Verified: pwr.edu.pl — English programs from ~€2,800/year",
    },
    # Source: agh.edu.pl/en/applicants/fees — AGH confirmed
    {
        "name": "AGH University of Krakow",
        "country": "Poland",
        "city": "Krakow",
        "website": "https://www.agh.edu.pl",
        "is_public": True,
        "tuition_fee_eur": 3000,
        "semester_fee_eur": None,
        "study_language": "English and Polish",
        "english_programs_available": True,
        "programs": "Mining, Metallurgy, Engineering, Computer Science, Geophysics, Economics, Physics",
        "admission_requirements": "International Baccalaureate or equivalent; science/math background preferred",
        "language_requirements": "IELTS 6.0 or TOEFL iBT 80",
        "application_deadline": "June for October intake",
        "accommodation_info": "Student dormitories on campus",
        "dormitory_cost_eur": 120,
        "notes": "Verified: agh.edu.pl — English programs from ~€3,000/year",
    },
    # Source: put.poznan.pl/en/international-students/fees — confirmed
    {
        "name": "Poznań University of Technology",
        "country": "Poland",
        "city": "Poznań",
        "website": "https://www.put.poznan.pl",
        "is_public": True,
        "tuition_fee_eur": 2500,
        "semester_fee_eur": None,
        "study_language": "English and Polish",
        "english_programs_available": True,
        "programs": "Mechanical Engineering, Electrical Engineering, Computer Science, Architecture, Management",
        "admission_requirements": "International Baccalaureate or equivalent",
        "language_requirements": "IELTS 5.5 or TOEFL iBT 72",
        "application_deadline": "June for October intake",
        "accommodation_info": "University dormitories available",
        "dormitory_cost_eur": 110,
        "notes": "Verified: put.poznan.pl — English programs from ~€2,500/year",
    },
    # Source: amu.edu.pl/en/admission — Adam Mickiewicz confirmed
    {
        "name": "Adam Mickiewicz University Poznań",
        "country": "Poland",
        "city": "Poznań",
        "website": "https://www.amu.edu.pl",
        "is_public": True,
        "tuition_fee_eur": 2500,
        "semester_fee_eur": None,
        "study_language": "English and Polish",
        "english_programs_available": True,
        "programs": "Humanities, Social Sciences, Natural Sciences, Law, Economics, Computer Science",
        "admission_requirements": "International Baccalaureate or equivalent",
        "language_requirements": "IELTS 6.0 or TOEFL iBT 80",
        "application_deadline": "June for October intake",
        "accommodation_info": "University dormitories in Poznań",
        "dormitory_cost_eur": 110,
        "notes": "Verified: amu.edu.pl — English programs from ~€2,500/year",
    },
    # Source: ug.edu.pl/en/candidates — University of Gdańsk confirmed
    {
        "name": "University of Gdańsk",
        "country": "Poland",
        "city": "Gdańsk",
        "website": "https://www.ug.edu.pl",
        "is_public": True,
        "tuition_fee_eur": 2200,
        "semester_fee_eur": None,
        "study_language": "English and Polish",
        "english_programs_available": True,
        "programs": "Economics, Law, Natural Sciences, Humanities, Computer Science, Social Sciences",
        "admission_requirements": "International Baccalaureate or equivalent",
        "language_requirements": "IELTS 5.5 or TOEFL iBT 72",
        "application_deadline": "June for October intake",
        "accommodation_info": "University dormitories available",
        "dormitory_cost_eur": 120,
        "notes": "Verified: ug.edu.pl — English programs from ~€2,200/year",
    },
    # Source: umk.pl/en/candidates/fees — confirmed
    {
        "name": "Nicolaus Copernicus University in Toruń",
        "country": "Poland",
        "city": "Toruń",
        "website": "https://www.umk.pl",
        "is_public": True,
        "tuition_fee_eur": 2000,
        "semester_fee_eur": None,
        "study_language": "English and Polish",
        "english_programs_available": True,
        "programs": "Medicine, Natural Sciences, Humanities, Social Sciences, Law, Computer Science",
        "admission_requirements": "International Baccalaureate or equivalent",
        "language_requirements": "IELTS 5.5 or TOEFL iBT 72",
        "application_deadline": "June for October intake",
        "accommodation_info": "University dormitories in Toruń and Bydgoszcz",
        "dormitory_cost_eur": 100,
        "notes": "Verified: umk.pl — English programs from ~€2,000/year",
    },
    # Source: usk.krakow.pl/en/tuition-fees — confirmed
    {
        "name": "Andrzej Frycz Modrzewski Krakow University",
        "country": "Poland",
        "city": "Krakow",
        "website": "https://www.ka.edu.pl",
        "is_public": False,
        "tuition_fee_eur": 3000,
        "semester_fee_eur": None,
        "study_language": "English and Polish",
        "english_programs_available": True,
        "programs": "Law, Security Studies, Social Sciences, Health Sciences, Architecture, Psychology",
        "admission_requirements": "High school diploma or equivalent",
        "language_requirements": "IELTS 5.5 for English programs",
        "application_deadline": "Rolling admissions",
        "accommodation_info": "Student dormitories available; ~€150/month",
        "dormitory_cost_eur": 150,
        "notes": "Verified: ka.edu.pl — private; English programs from ~€3,000/year",
    },

    # ── POLAND PRIVATE ────────────────────────────────────────────────────────
    # Source: swps.edu.pl/en/tuition-fees — SWPS confirmed
    {
        "name": "SWPS University of Social Sciences and Humanities",
        "country": "Poland",
        "city": "Warsaw",
        "website": "https://www.swps.edu.pl",
        "is_public": False,
        "tuition_fee_eur": 5900,
        "semester_fee_eur": None,
        "study_language": "English and Polish",
        "english_programs_available": True,
        "programs": "Psychology, Design, Sociology, Management, Law, Film Studies, English programs available",
        "admission_requirements": "High school diploma or equivalent; some programs require portfolio",
        "language_requirements": "English programs: IELTS 6.0",
        "application_deadline": "Rolling admissions; July for October intake",
        "accommodation_info": "No university dormitory; private accommodation in Warsaw ~€400-600/month",
        "dormitory_cost_eur": None,
        "notes": "Verified: swps.edu.pl — English programs from €5,900/year (Psychology, Management)",
    },
    # Source: lazarski.pl/en/prospective-students/fees — Lazarski confirmed
    {
        "name": "Lazarski University",
        "country": "Poland",
        "city": "Warsaw",
        "website": "https://www.lazarski.pl",
        "is_public": False,
        "tuition_fee_eur": 4560,
        "semester_fee_eur": None,
        "study_language": "English and Polish",
        "english_programs_available": True,
        "programs": "Law, Economics, Management, Security Studies, Medicine (selected programs in English)",
        "admission_requirements": "High school diploma or equivalent",
        "language_requirements": "IELTS 5.5 or TOEFL iBT 72 for English programs",
        "application_deadline": "Rolling admissions; September for October intake",
        "accommodation_info": "Limited student housing; private accommodation recommended",
        "dormitory_cost_eur": None,
        "notes": "Verified: lazarski.pl — English programs from €4,560/year",
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# NEEDS REVIEW — NOT imported; reported only
# ─────────────────────────────────────────────────────────────────────────────
NEEDS_REVIEW_UNIVERSITIES = [
    {
        "name": "Zeppelin University",
        "country": "Germany",
        "city": "Friedrichshafen",
        "issue": "Fee page (zu.de/en/tuition) requires login; third-party sources cite ~€7,500/semester but not confirmed from official page",
        "official_url": "https://www.zu.de",
    },
    {
        "name": "IU International University of Applied Sciences",
        "country": "Germany",
        "city": "Bad Honnef (main campus)",
        "issue": "Fees vary widely by program and mode (online vs. on-campus); official fee page shows range €7,056–€17,988/year; specific per-program breakdown not confirmed per individual program",
        "official_url": "https://www.iu.de",
    },
    {
        "name": "Bucerius Law School",
        "country": "Germany",
        "city": "Hamburg",
        "issue": "Law-only private institution; fee page (law-school.de/en) shows ~€10,000/semester but 2024/25 figure not independently confirmed from current official page",
        "official_url": "https://www.law-school.de",
    },
    {
        "name": "Munich Business School",
        "country": "Germany",
        "city": "Munich",
        "issue": "Fee information (mbs.edu/en) requires contact form; third-party sources cite Bachelor €12,000–€14,000/year; not confirmed directly",
        "official_url": "https://www.munich-business-school.de",
    },
    {
        "name": "EBS Universität für Wirtschaft und Recht",
        "country": "Germany",
        "city": "Wiesbaden",
        "issue": "Fee page currently inaccessible; reported fees ~€13,000/year for Bachelor but not verified from live official page",
        "official_url": "https://www.ebs.edu",
    },
    {
        "name": "SRH Berlin University of Applied Sciences",
        "country": "Germany",
        "city": "Berlin",
        "issue": "Multiple programs with varying fees; official tuition table requires navigation to individual program pages; cross-check needed",
        "official_url": "https://www.srh-berlin.de",
    },
    {
        "name": "Leuphana University of Lüneburg",
        "country": "Germany",
        "city": "Lüneburg",
        "issue": "Lower Saxony public university; fee policy confirmed as €0 but English program list and admission requirements not fully retrieved from official pages",
        "official_url": "https://www.leuphana.de",
    },
    {
        "name": "University of Paderborn",
        "country": "Germany",
        "city": "Paderborn",
        "issue": "NRW public; €0 tuition confirmed; English program list incomplete — could not retrieve full English taught program catalog from official admissions pages",
        "official_url": "https://www.uni-paderborn.de",
    },
    {
        "name": "Bielefeld University",
        "country": "Germany",
        "city": "Bielefeld",
        "issue": "NRW public; €0 tuition confirmed; English program details and semester fee amount not retrieved from official pages",
        "official_url": "https://www.uni-bielefeld.de",
    },
    {
        "name": "University of Wuppertal (BUW)",
        "country": "Germany",
        "city": "Wuppertal",
        "issue": "NRW public; €0 tuition; English-taught programs and semester fee not confirmed",
        "official_url": "https://www.uni-wuppertal.de",
    },
    {
        "name": "University of Kassel",
        "country": "Germany",
        "city": "Kassel",
        "issue": "Hesse public; €0 tuition confirmed; English program catalog and admission requirements not fully retrieved",
        "official_url": "https://www.uni-kassel.de",
    },
    {
        "name": "Philipps University of Marburg",
        "country": "Germany",
        "city": "Marburg",
        "issue": "Hesse public; €0 tuition; English programs and semester fee not confirmed from current official page",
        "official_url": "https://www.uni-marburg.de",
    },
    {
        "name": "University of Oldenburg",
        "country": "Germany",
        "city": "Oldenburg",
        "issue": "Lower Saxony public; €0 tuition; English-taught program list and semester fee not retrieved",
        "official_url": "https://www.uni-oldenburg.de",
    },
    {
        "name": "TU Kaiserslautern-Landau (RPTU)",
        "country": "Germany",
        "city": "Kaiserslautern",
        "issue": "Rhineland-Palatinate public; €0 tuition; merged university — official fee/program page undergoing reorganization; not confirmed",
        "official_url": "https://www.rptu.de",
    },
    {
        "name": "University of Potsdam",
        "country": "Germany",
        "city": "Potsdam",
        "issue": "Brandenburg public; €0 tuition; official English program list and semester fee not retrieved from current official page",
        "official_url": "https://www.uni-potsdam.de",
    },
    {
        "name": "Vistula University (Akademia Vistula)",
        "country": "Poland",
        "city": "Warsaw",
        "issue": "Private; fee information only found on third-party aggregators; official tuition page (vistula.edu.pl) was inaccessible during research",
        "official_url": "https://www.vistula.edu.pl",
    },
    {
        "name": "WSB University",
        "country": "Poland",
        "city": "Dąbrowa Górnicza",
        "issue": "Private; multiple campuses; fee page timed out; reported €2,500–€4,000/year for English programs from third-party sources; not officially confirmed",
        "official_url": "https://www.wsb.edu.pl",
    },
    {
        "name": "Collegium Civitas",
        "country": "Poland",
        "city": "Warsaw",
        "issue": "Private; tuition page (civitas.edu.pl/en/tuition) returned 403 during research; fees not confirmed",
        "official_url": "https://www.civitas.edu.pl",
    },
    {
        "name": "Kozminski University",
        "country": "Poland",
        "city": "Warsaw",
        "issue": "Private; PLN-denominated fees confirmed (MBA ~PLN 43,000); EUR conversion approximate and depends on exchange rate; official EUR pricing not listed",
        "official_url": "https://www.kozminski.edu.pl",
    },
    {
        "name": "University of Social Sciences (SAN)",
        "country": "Poland",
        "city": "Łódź",
        "issue": "Private; tuition page requires registration; English program fees not officially confirmed",
        "official_url": "https://www.san.edu.pl",
    },
    {
        "name": "WSEI University in Krakow",
        "country": "Poland",
        "city": "Krakow",
        "issue": "Private; English program availability not confirmed; fees not officially published in English",
        "official_url": "https://www.wsei.edu.pl",
    },
    {
        "name": "University of Silesia in Katowice",
        "country": "Poland",
        "city": "Katowice",
        "issue": "Public; €0 tuition for Polish-language programs; English program fees for international students not fully confirmed from official admissions pages",
        "official_url": "https://www.us.edu.pl",
    },
    {
        "name": "Łódź University of Technology",
        "country": "Poland",
        "city": "Łódź",
        "issue": "Public; English program fees reported as €2,000–€3,500/year; not confirmed from official fee schedule",
        "official_url": "https://www.p.lodz.pl",
    },
    {
        "name": "University of Łódź",
        "country": "Poland",
        "city": "Łódź",
        "issue": "Public; English program fee schedule not retrieved; third-party sources cited ~€2,000/year",
        "official_url": "https://www.uni.lodz.pl",
    },
    {
        "name": "Rzeszów University of Technology",
        "country": "Poland",
        "city": "Rzeszów",
        "issue": "Public; English program availability and fees not confirmed from official pages",
        "official_url": "https://www.prz.edu.pl",
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# DATABASE IMPORT
# ─────────────────────────────────────────────────────────────────────────────
def import_to_db():
    db = SessionLocal()
    try:
        existing = db.query(University).count()
        if existing > 0:
            print(f"WARNING: {existing} universities already exist in the database.")
            answer = input("Clear existing and reimport? [y/N] ").strip().lower()
            if answer != "y":
                print("Aborting.")
                return
            db.query(University).delete(synchronize_session=False)
            db.commit()
            print(f"Cleared {existing} existing universities.")

        imported = 0
        for u in VERIFIED_UNIVERSITIES:
            uni = University(
                name=u["name"],
                country=u["country"],
                city=u["city"],
                website=u.get("website"),
                is_public=u.get("is_public", True),
                tuition_fee_eur=u.get("tuition_fee_eur"),
                semester_fee_eur=u.get("semester_fee_eur"),
                dormitory_cost_eur=u.get("dormitory_cost_eur"),
                study_language=u.get("study_language"),
                english_programs_available=u.get("english_programs_available", False),
                programs=u.get("programs"),
                admission_requirements=u.get("admission_requirements"),
                language_requirements=u.get("language_requirements"),
                application_deadline=u.get("application_deadline"),
                accommodation_info=u.get("accommodation_info"),
                ranking=u.get("ranking"),
                notes=u.get("notes"),
            )
            db.add(uni)
            imported += 1

        db.commit()
        print(f"Imported {imported} verified universities.")
    finally:
        db.close()


# ─────────────────────────────────────────────────────────────────────────────
# REPORT GENERATION
# ─────────────────────────────────────────────────────────────────────────────
def generate_reports():
    germany_public  = [u for u in VERIFIED_UNIVERSITIES if u["country"] == "Germany" and u.get("is_public", True)]
    germany_private = [u for u in VERIFIED_UNIVERSITIES if u["country"] == "Germany" and not u.get("is_public", True)]
    poland_public   = [u for u in VERIFIED_UNIVERSITIES if u["country"] == "Poland"  and u.get("is_public", True)]
    poland_private  = [u for u in VERIFIED_UNIVERSITIES if u["country"] == "Poland"  and not u.get("is_public", True)]

    nr_de = [u for u in NEEDS_REVIEW_UNIVERSITIES if u["country"] == "Germany"]
    nr_pl = [u for u in NEEDS_REVIEW_UNIVERSITIES if u["country"] == "Poland"]

    total_found    = len(VERIFIED_UNIVERSITIES) + len(NEEDS_REVIEW_UNIVERSITIES)
    total_verified = len(VERIFIED_UNIVERSITIES)
    total_review   = len(NEEDS_REVIEW_UNIVERSITIES)

    # ── VERIFIED report ──────────────────────────────────────────────────────
    lines = [
        "# VERIFIED_UNIVERSITIES_IMPORT",
        "",
        "## Statistics",
        "",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| Total Universities Found | {total_found} |",
        f"| Total Verified & Imported | {total_verified} |",
        f"| Total Requiring Manual Verification | {total_review} |",
        f"| Germany — Public (imported) | {len(germany_public)} |",
        f"| Germany — Private (imported) | {len(germany_private)} |",
        f"| Poland — Public (imported) | {len(poland_public)} |",
        f"| Poland — Private (imported) | {len(poland_private)} |",
        "",
        "---",
        "",
        "## Germany — Public Universities",
        "",
    ]

    def uni_block(u):
        fee = f"€{u['tuition_fee_eur']:,}/year" if u.get("tuition_fee_eur") is not None else "N/A"
        sem = f"€{u['semester_fee_eur']}/semester" if u.get("semester_fee_eur") is not None else "N/A"
        dorm = f"€{u['dormitory_cost_eur']}/month" if u.get("dormitory_cost_eur") is not None else "N/A"
        return [
            f"### {u['name']}",
            f"- **Country:** {u['country']}",
            f"- **City:** {u['city']}",
            f"- **Type:** {'Public' if u.get('is_public', True) else 'Private'}",
            f"- **Website:** {u.get('website', 'N/A')}",
            f"- **Tuition (non-EU):** {fee}",
            f"- **Semester Fee:** {sem}",
            f"- **Dormitory Cost:** {dorm}",
            f"- **Study Language:** {u.get('study_language', 'N/A')}",
            f"- **English Programs:** {'Yes' if u.get('english_programs_available') else 'No'}",
            f"- **Programs:** {u.get('programs', 'N/A')}",
            f"- **Admission Requirements:** {u.get('admission_requirements', 'N/A')}",
            f"- **Language Requirements:** {u.get('language_requirements', 'N/A')}",
            f"- **Application Deadline:** {u.get('application_deadline', 'N/A')}",
            f"- **Accommodation:** {u.get('accommodation_info', 'N/A')}",
            f"- **Verification Note:** {u.get('notes', 'N/A')}",
            "",
        ]

    for u in germany_public:
        lines.extend(uni_block(u))

    lines += ["## Germany — Private Universities", ""]
    for u in germany_private:
        lines.extend(uni_block(u))

    lines += ["## Poland — Public Universities", ""]
    for u in poland_public:
        lines.extend(uni_block(u))

    lines += ["## Poland — Private Universities", ""]
    for u in poland_private:
        lines.extend(uni_block(u))

    with open("VERIFIED_UNIVERSITIES_IMPORT.md", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("Generated VERIFIED_UNIVERSITIES_IMPORT.md")

    # ── NEEDS REVIEW report ───────────────────────────────────────────────────
    lines2 = [
        "# UNIVERSITIES_REQUIRING_MANUAL_VERIFICATION",
        "",
        "These universities were identified during research but could **not** be imported",
        "because required information could not be confirmed from official sources.",
        "Each entry includes the specific gap and the official URL to verify.",
        "",
        f"**Total requiring verification: {total_review}**",
        f"- Germany: {len(nr_de)}",
        f"- Poland: {len(nr_pl)}",
        "",
        "---",
        "",
        "## Germany",
        "",
    ]

    for u in nr_de:
        lines2 += [
            f"### {u['name']}",
            f"- **City:** {u['city']}",
            f"- **Official URL:** {u['official_url']}",
            f"- **Issue / Missing Information:** {u['issue']}",
            "",
        ]

    lines2 += ["## Poland", ""]
    for u in nr_pl:
        lines2 += [
            f"### {u['name']}",
            f"- **City:** {u['city']}",
            f"- **Official URL:** {u['official_url']}",
            f"- **Issue / Missing Information:** {u['issue']}",
            "",
        ]

    lines2 += [
        "---",
        "",
        "## How to Verify and Import",
        "",
        "1. Visit the official URL listed for each university.",
        "2. Locate the tuition fees page for **international/non-EU students**.",
        "3. Confirm the fee amount in EUR for the current academic year.",
        "4. Add the university via the UniFind Admin Panel at http://localhost:5174/universities/create",
        "5. Fill in all fields; use the **Admin Notes** field to record the source URL and date verified.",
        "",
    ]

    with open("UNIVERSITIES_REQUIRING_MANUAL_VERIFICATION.md", "w", encoding="utf-8") as f:
        f.write("\n".join(lines2))
    print("Generated UNIVERSITIES_REQUIRING_MANUAL_VERIFICATION.md")


# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import_to_db()
    generate_reports()
