"""add_university_detail_fields

Revision ID: a87a7567641c
Revises: 50f934b97500
Create Date: 2026-06-20 07:50:03.688548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87a7567641c'
down_revision: Union[str, None] = '50f934b97500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('programs', sa.Text(), nullable=True))
    op.add_column('universities', sa.Column('admission_requirements', sa.Text(), nullable=True))
    op.add_column('universities', sa.Column('required_documents', sa.Text(), nullable=True))
    op.add_column('universities', sa.Column('application_deadline', sa.String(length=200), nullable=True))
    op.add_column('universities', sa.Column('language_requirements', sa.Text(), nullable=True))
    op.add_column('universities', sa.Column('study_duration', sa.String(length=200), nullable=True))
    op.add_column('universities', sa.Column('accommodation_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'accommodation_info')
    op.drop_column('universities', 'study_duration')
    op.drop_column('universities', 'language_requirements')
    op.drop_column('universities', 'application_deadline')
    op.drop_column('universities', 'required_documents')
    op.drop_column('universities', 'admission_requirements')
    op.drop_column('universities', 'programs')
    # ### end Alembic commands ###
