"""add_university_extended_fields

Revision ID: bcb0be2e0b3d
Revises: a87a7567641c
Create Date: 2026-06-20 08:20:14.602448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb0be2e0b3d'
down_revision: Union[str, None] = 'a87a7567641c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('application_fee_eur', sa.Integer(), nullable=True))
    op.add_column('universities', sa.Column('living_cost_eur', sa.Integer(), nullable=True))
    op.add_column('universities', sa.Column('min_gpa', sa.Float(), nullable=True))
    op.add_column('universities', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('universities', sa.Column('contact_email', sa.String(length=200), nullable=True))
    op.add_column('universities', sa.Column('contact_phone', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'contact_phone')
    op.drop_column('universities', 'contact_email')
    op.drop_column('universities', 'logo_url')
    op.drop_column('universities', 'min_gpa')
    op.drop_column('universities', 'living_cost_eur')
    op.drop_column('universities', 'application_fee_eur')
    # ### end Alembic commands ###
