"""add_university_programs_table

Revision ID: f739d93e8523
Revises: x6y7z8a9b0c1
Create Date: 2026-07-04 07:02:58.724127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f739d93e8523'
down_revision: Union[str, None] = 'x6y7z8a9b0c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('field_of_study', sa.String(length=150), nullable=False),
    sa.Column('degree_level', sa.String(length=20), nullable=False),
    sa.Column('tuition_fee_eur', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_programs_id'), 'university_programs', ['id'], unique=False)
    op.create_index(op.f('ix_university_programs_university_id'), 'university_programs', ['university_id'], unique=False)
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_application_documents_application_id'), table_name='application_documents')
    op.drop_index(op.f('ix_application_documents_id'), table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_table('announcement_reads')
    op.drop_index(op.f('ix_inbound_emails_id'), table_name='inbound_emails')
    op.drop_table('inbound_emails')
    op.drop_index(op.f('ix_application_pipeline_id'), table_name='application_pipeline')
    op.drop_index(op.f('ix_application_pipeline_user_id'), table_name='application_pipeline')
    op.drop_table('application_pipeline')
    op.drop_index(op.f('ix_student_documents_id'), table_name='student_documents')
    op.drop_index(op.f('ix_student_documents_user_id'), table_name='student_documents')
    op.drop_table('student_documents')
    op.drop_index(op.f('ix_motivation_letters_id'), table_name='motivation_letters')
    op.drop_index(op.f('ix_motivation_letters_user_id'), table_name='motivation_letters')
    op.drop_table('motivation_letters')
    op.drop_index(op.f('ix_course_chat_messages_course_id'), table_name='course_chat_messages')
    op.drop_index(op.f('ix_course_chat_messages_id'), table_name='course_chat_messages')
    op.drop_table('course_chat_messages')
    op.drop_index(op.f('ix_linked_emails_id'), table_name='linked_emails')
    op.drop_table('linked_emails')
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ielts_tests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('instructors_user_id_key'), 'instructors', type_='unique')
    op.drop_index(op.f('ix_instructors_user_id'), table_name='instructors')
    op.create_index(op.f('ix_instructors_user_id'), 'instructors', ['user_id'], unique=True)
    op.alter_column('lessons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('placement_test_questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('placement_tests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('student_profiles', 'placement_results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_profiles', 'placement_results',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('placement_tests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('placement_test_questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lessons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_instructors_user_id'), table_name='instructors')
    op.create_index(op.f('ix_instructors_user_id'), 'instructors', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('instructors_user_id_key'), 'instructors', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ielts_tests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('linked_emails',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('linked_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('consent_given_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('consent_ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('consent_version', sa.VARCHAR(length=20), server_default=sa.text("'1.0'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('forwarding_confirmed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('linked_emails_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('linked_emails_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('linked_emails_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_linked_emails_id'), 'linked_emails', ['id'], unique=False)
    op.create_table('course_chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('course_chat_messages_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('course_chat_messages_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('course_chat_messages_pkey'))
    )
    op.create_index(op.f('ix_course_chat_messages_id'), 'course_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_course_chat_messages_course_id'), 'course_chat_messages', ['course_id'], unique=False)
    op.create_table('motivation_letters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('university_name', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('program', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('motivation_letters_university_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('motivation_letters_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('motivation_letters_pkey'))
    )
    op.create_index(op.f('ix_motivation_letters_user_id'), 'motivation_letters', ['user_id'], unique=False)
    op.create_index(op.f('ix_motivation_letters_id'), 'motivation_letters', ['id'], unique=False)
    op.create_table('student_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('doc_type', sa.VARCHAR(length=50), server_default=sa.text("'other'::character varying"), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('student_documents_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_documents_pkey'))
    )
    op.create_index(op.f('ix_student_documents_user_id'), 'student_documents', ['user_id'], unique=False)
    op.create_index(op.f('ix_student_documents_id'), 'student_documents', ['id'], unique=False)
    op.create_table('application_pipeline',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'shortlisted'::character varying"), autoincrement=False, nullable=False),
    sa.Column('fit_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fit_analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fit_gaps', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motivation_letter', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checklist', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deadline_note', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('application_pipeline_university_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('application_pipeline_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('application_pipeline_pkey')),
    sa.UniqueConstraint('user_id', 'university_id', name=op.f('uq_pipeline_user_uni'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_application_pipeline_user_id'), 'application_pipeline', ['user_id'], unique=False)
    op.create_index(op.f('ix_application_pipeline_id'), 'application_pipeline', ['id'], unique=False)
    op.create_table('inbound_emails',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=500), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('body_preview', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('detected_university', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('detected_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('inbound_emails_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inbound_emails_pkey'))
    )
    op.create_index(op.f('ix_inbound_emails_id'), 'inbound_emails', ['id'], unique=False)
    op.create_table('announcement_reads',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('announcement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name=op.f('announcement_reads_announcement_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('announcement_reads_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'announcement_id', name=op.f('announcement_reads_pkey'))
    )
    op.create_table('application_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_approved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('application_documents_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('application_documents_pkey'))
    )
    op.create_index(op.f('ix_application_documents_id'), 'application_documents', ['id'], unique=False)
    op.create_index(op.f('ix_application_documents_application_id'), 'application_documents', ['application_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), server_default=sa.text("'info'::character varying"), autoincrement=False, nullable=False),
    sa.Column('university_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False),
    sa.Column('inbound_email_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_done', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['inbound_email_id'], ['inbound_emails.id'], name=op.f('calendar_events_inbound_email_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('calendar_events_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('calendar_events_pkey'))
    )
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.drop_index(op.f('ix_university_programs_university_id'), table_name='university_programs')
    op.drop_index(op.f('ix_university_programs_id'), table_name='university_programs')
    op.drop_table('university_programs')
    # ### end Alembic commands ###
