import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.stdout.reconfigure(encoding="utf-8")

from app.database import SessionLocal
import sqlalchemy as sa

db = SessionLocal()


def get_existing_names():
    rows = db.execute(sa.text("SELECT name FROM universities")).fetchall()
    return {r[0] for r in rows}


def insert_university(data):
    result = db.execute(
        sa.text("""
            INSERT INTO universities
            (name, country, city, website, description, ranking, tuition_fee_eur,
             is_public, english_programs_available, programs, application_method,
             application_portal_url, semester_fee_eur, notes)
            VALUES
            (:name, :country, :city, :website, :description, :ranking, :tuition_fee_eur,
             :is_public, :english_programs_available, :programs, :application_method,
             :application_portal_url, :semester_fee_eur, :notes)
            RETURNING id
        """),
        data
    )
    return result.fetchone()[0]


def insert_programs(uni_id, programs):
    for p in programs:
        db.execute(
            sa.text("""
                INSERT INTO university_programs
                (university_id, field_of_study, degree_level, tuition_fee_eur, notes)
                VALUES (:university_id, :field_of_study, :degree_level, :tuition_fee_eur, :notes)
            """),
            {**p, "university_id": uni_id}
        )


existing = get_existing_names()

UNIVERSITIES = [
    # ===== CLASSICAL / COMPREHENSIVE UNIVERSITIES =====
    {
        "name": "University of Bialystok",
        "country": "Poland",
        "city": "Bialystok",
        "website": "https://uwb.edu.pl/en",
        "description": "Public research university in northeastern Poland offering law, economics, biology, mathematics, history, and social sciences.",
        "ranking": 601,
        "tuition_fee_eur": 3500,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Law, Economics, Biology, Mathematics, History, Social Sciences",
        "application_method": "irk",
        "application_portal_url": "https://irk.uwb.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~3,500–4,000 EUR/yr depending on field. Source: uwb.edu.pl/en/admissions/tuition-fees",
        "programs_list": [
            {"field_of_study": "Law", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Economics & Finance", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Biology & Natural Sciences", "degree_level": "bachelor", "tuition_fee_eur": 4000, "notes": "~4,000 EUR/yr non-EU"},
            {"field_of_study": "Mathematics & Computer Science", "degree_level": "bachelor", "tuition_fee_eur": 3800, "notes": "~3,800 EUR/yr non-EU"},
            {"field_of_study": "Law", "degree_level": "master", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Economics", "degree_level": "master", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD doctoral schools free in Poland for admitted students"},
        ],
    },
    {
        "name": "Kazimierz Wielki University in Bydgoszcz",
        "country": "Poland",
        "city": "Bydgoszcz",
        "website": "https://www.ukw.edu.pl/en",
        "description": "Public university in Bydgoszcz offering humanities, social sciences, natural sciences, education, and physical culture.",
        "ranking": 701,
        "tuition_fee_eur": 2800,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Humanities, Social Sciences, Natural Sciences, Education, Physical Culture",
        "application_method": "irk",
        "application_portal_url": "https://irk.ukw.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU students: ~2,800–3,500 EUR/yr. Source: ukw.edu.pl",
        "programs_list": [
            {"field_of_study": "Humanities & Social Sciences", "degree_level": "bachelor", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "Natural Sciences", "degree_level": "bachelor", "tuition_fee_eur": 3200, "notes": "~3,200 EUR/yr non-EU"},
            {"field_of_study": "Education", "degree_level": "bachelor", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "Humanities", "degree_level": "master", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "University of Warmia and Mazury in Olsztyn",
        "country": "Poland",
        "city": "Olsztyn",
        "website": "https://www.uwm.edu.pl/en",
        "description": "Large public university in northeastern Poland offering agriculture, veterinary medicine, food sciences, engineering, humanities, and medical sciences.",
        "ranking": 601,
        "tuition_fee_eur": 3500,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Agriculture, Veterinary Medicine, Food Science, Engineering, Humanities, Medicine",
        "application_method": "irk",
        "application_portal_url": "https://irk.uwm.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: 3,000–6,000 EUR/yr by field. Medicine and Vet programs significantly higher.",
        "programs_list": [
            {"field_of_study": "Agriculture & Food Science", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Engineering & Technical", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Humanities & Social Sciences", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Veterinary Medicine", "degree_level": "bachelor", "tuition_fee_eur": 9000, "notes": "~9,000 EUR/yr — veterinary program"},
            {"field_of_study": "Agriculture", "degree_level": "master", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Engineering", "degree_level": "master", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "University of Opole",
        "country": "Poland",
        "city": "Opole",
        "website": "https://www.uni.opole.pl/en",
        "description": "Public research university in southwestern Poland offering humanities, sciences, law, economics, theology, and natural sciences.",
        "ranking": 701,
        "tuition_fee_eur": 3000,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Humanities, Sciences, Law, Economics, Theology, Natural Sciences",
        "application_method": "irk",
        "application_portal_url": "https://irk.uni.opole.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~3,000–4,000 EUR/yr by field. Source: uni.opole.pl",
        "programs_list": [
            {"field_of_study": "Humanities & Social Sciences", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Natural Sciences", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Law & Economics", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Humanities", "degree_level": "master", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "University of Rzeszow",
        "country": "Poland",
        "city": "Rzeszów",
        "website": "https://www.ur.edu.pl/en",
        "description": "Large public university in southeastern Poland offering medicine, dentistry, humanities, sciences, agriculture, and social sciences.",
        "ranking": 601,
        "tuition_fee_eur": 3500,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Medicine, Dentistry, Humanities, Sciences, Agriculture, Social Sciences",
        "application_method": "irk",
        "application_portal_url": "https://irk.ur.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU students vary by field. Source: ur.edu.pl/en/incoming-students/fees-payable",
        "programs_list": [
            {"field_of_study": "Medicine", "degree_level": "bachelor", "tuition_fee_eur": 12000, "notes": "Medicine program ~12,000 EUR/yr non-EU"},
            {"field_of_study": "Dentistry", "degree_level": "bachelor", "tuition_fee_eur": 13000, "notes": "Dentistry ~13,000 EUR/yr non-EU"},
            {"field_of_study": "Humanities & Social Sciences", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Natural Sciences", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Agriculture", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Humanities", "degree_level": "master", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "University of Szczecin",
        "country": "Poland",
        "city": "Szczecin",
        "website": "https://www.usz.edu.pl/en",
        "description": "Public research university in northwestern Poland offering economics, law, humanities, sciences, management, and physical education.",
        "ranking": 601,
        "tuition_fee_eur": 3000,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Economics, Law, Humanities, Sciences, Management, Physical Education",
        "application_method": "irk",
        "application_portal_url": "https://irk.usz.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~3,000–4,000 EUR/yr by field. Source: usz.edu.pl",
        "programs_list": [
            {"field_of_study": "Economics & Finance", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Law", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Humanities & Social Sciences", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Natural Sciences", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Economics", "degree_level": "master", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Cardinal Stefan Wyszynski University in Warsaw",
        "country": "Poland",
        "city": "Warsaw",
        "website": "https://www.uksw.edu.pl/en",
        "description": "Public Catholic university in Warsaw offering law, theology, philosophy, social sciences, humanities, and natural sciences.",
        "ranking": 601,
        "tuition_fee_eur": 3500,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Law, Theology, Philosophy, Social Sciences, Humanities, Natural Sciences",
        "application_method": "irk",
        "application_portal_url": "https://irk.uksw.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~3,000–4,000 EUR/yr. Source: uksw.edu.pl",
        "programs_list": [
            {"field_of_study": "Law", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Theology & Philosophy", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Social Sciences & Humanities", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Natural Sciences", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Law", "degree_level": "master", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "University of Zielona Gora",
        "country": "Poland",
        "city": "Zielona Góra",
        "website": "https://www.uz.zgora.pl/en",
        "description": "Public university in western Poland offering engineering, humanities, economics, and health sciences. One of the youngest Polish universities.",
        "ranking": 701,
        "tuition_fee_eur": 3000,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Engineering, Humanities, Economics, Health Sciences",
        "application_method": "irk",
        "application_portal_url": "https://irk.uz.zgora.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~2,800–3,500 EUR/yr. Source: uz.zgora.pl",
        "programs_list": [
            {"field_of_study": "Engineering & Technology", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Humanities & Social Sciences", "degree_level": "bachelor", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "Economics", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Engineering", "degree_level": "master", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Jan Kochanowski University in Kielce",
        "country": "Poland",
        "city": "Kielce",
        "website": "https://www.ujk.edu.pl/en",
        "description": "Public university in south-central Poland offering humanities, social sciences, natural sciences, health, and arts.",
        "ranking": 701,
        "tuition_fee_eur": 2800,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Humanities, Social Sciences, Natural Sciences, Health, Arts",
        "application_method": "irk",
        "application_portal_url": "https://irk.ujk.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~2,800–3,500 EUR/yr. Source: ujk.edu.pl",
        "programs_list": [
            {"field_of_study": "Humanities & Social Sciences", "degree_level": "bachelor", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "Natural Sciences & Health", "degree_level": "bachelor", "tuition_fee_eur": 3200, "notes": "~3,200 EUR/yr non-EU"},
            {"field_of_study": "Humanities", "degree_level": "master", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "John Paul II Catholic University of Lublin",
        "country": "Poland",
        "city": "Lublin",
        "website": "https://www.kul.pl/en",
        "description": "One of the oldest Catholic universities in Central-Eastern Europe. Offers theology, philosophy, law, humanities, social sciences, and mathematics.",
        "ranking": 501,
        "tuition_fee_eur": 4000,
        "is_public": False,
        "english_programs_available": True,
        "programs": "Theology, Philosophy, Law, Humanities, Social Sciences, Mathematics",
        "application_method": "own_portal",
        "application_portal_url": "https://rekrutacja.kul.pl",
        "semester_fee_eur": 0,
        "notes": "Private Catholic university. Fees for non-EU: ~4,000–5,000 EUR/yr. Source: kandydat.kul.pl/en/tuition-fees",
        "programs_list": [
            {"field_of_study": "Theology & Philosophy", "degree_level": "bachelor", "tuition_fee_eur": 3800, "notes": "~3,800 EUR/yr non-EU"},
            {"field_of_study": "Law", "degree_level": "bachelor", "tuition_fee_eur": 4500, "notes": "~4,500 EUR/yr non-EU"},
            {"field_of_study": "Humanities & Social Sciences", "degree_level": "bachelor", "tuition_fee_eur": 4000, "notes": "~4,000 EUR/yr non-EU"},
            {"field_of_study": "Theology", "degree_level": "master", "tuition_fee_eur": 3800, "notes": "~3,800 EUR/yr non-EU"},
            {"field_of_study": "Law", "degree_level": "master", "tuition_fee_eur": 4500, "notes": "~4,500 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },

    # ===== TECHNICAL UNIVERSITIES =====
    {
        "name": "Bialystok University of Technology",
        "country": "Poland",
        "city": "Bialystok",
        "website": "https://pb.edu.pl/en",
        "description": "Public technical university in northeastern Poland offering civil engineering, architecture, mechanical engineering, electrical engineering, and computer science.",
        "ranking": 601,
        "tuition_fee_eur": 3300,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Civil Engineering, Architecture, Mechanical Engineering, Electrical Engineering, Computer Science",
        "application_method": "own_portal",
        "application_portal_url": "https://apply.pb.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: 3,000–3,600 EUR/yr. Source: pb.edu.pl",
        "programs_list": [
            {"field_of_study": "Civil & Environmental Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3300, "notes": "~3,000–3,600 EUR/yr non-EU"},
            {"field_of_study": "Mechanical Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3300, "notes": "~3,000–3,600 EUR/yr non-EU"},
            {"field_of_study": "Computer Science", "degree_level": "bachelor", "tuition_fee_eur": 3300, "notes": "~3,000–3,600 EUR/yr non-EU"},
            {"field_of_study": "Architecture", "degree_level": "bachelor", "tuition_fee_eur": 3600, "notes": "~3,600 EUR/yr non-EU"},
            {"field_of_study": "Electrical Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3300, "notes": "~3,300 EUR/yr non-EU"},
            {"field_of_study": "Engineering", "degree_level": "master", "tuition_fee_eur": 3300, "notes": "~3,300 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Czestochowa University of Technology",
        "country": "Poland",
        "city": "Czestochowa",
        "website": "https://pcz.pl/en",
        "description": "Public technical university in south-central Poland offering mechanical engineering, electrical engineering, civil engineering, management, and environmental engineering.",
        "ranking": 701,
        "tuition_fee_eur": 3000,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Mechanical Engineering, Electrical Engineering, Civil Engineering, Management, Environmental Engineering",
        "application_method": "own_portal",
        "application_portal_url": "https://rekrutacja.pcz.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~3,000–3,500 EUR/yr. Source: pcz.pl",
        "programs_list": [
            {"field_of_study": "Mechanical Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Civil Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Management & Production Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Engineering", "degree_level": "master", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Kielce University of Technology",
        "country": "Poland",
        "city": "Kielce",
        "website": "https://tu.kielce.pl/en",
        "description": "Public technical university in central Poland offering civil engineering, mechanical engineering, electrical engineering, and management.",
        "ranking": 701,
        "tuition_fee_eur": 2800,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Civil Engineering, Mechanical Engineering, Electrical Engineering, Management",
        "application_method": "own_portal",
        "application_portal_url": "https://rekrutacja.tu.kielce.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~2,800–3,200 EUR/yr. Source: tu.kielce.pl",
        "programs_list": [
            {"field_of_study": "Civil Engineering", "degree_level": "bachelor", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "Mechanical Engineering", "degree_level": "bachelor", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "Electrical Engineering", "degree_level": "bachelor", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "Engineering", "degree_level": "master", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Koszalin University of Technology",
        "country": "Poland",
        "city": "Koszalin",
        "website": "https://tu.koszalin.pl/en",
        "description": "Public technical university on the northern coast of Poland offering mechanical engineering, civil engineering, electronics, and management.",
        "ranking": 701,
        "tuition_fee_eur": 2800,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Mechanical Engineering, Civil Engineering, Electronics, Management",
        "application_method": "own_portal",
        "application_portal_url": "https://rekrutacja.tu.koszalin.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~2,800–3,200 EUR/yr. Source: tu.koszalin.pl",
        "programs_list": [
            {"field_of_study": "Mechanical Engineering", "degree_level": "bachelor", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "Civil Engineering", "degree_level": "bachelor", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "Electronics & Telecommunications", "degree_level": "bachelor", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "Engineering", "degree_level": "master", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Lublin University of Technology",
        "country": "Poland",
        "city": "Lublin",
        "website": "https://pollub.pl/en",
        "description": "Public technical university in eastern Poland offering computer science, civil engineering, mechanical engineering, electrical engineering, and management.",
        "ranking": 601,
        "tuition_fee_eur": 4000,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Computer Science, Civil Engineering, Mechanical Engineering, Electrical Engineering, Management",
        "application_method": "own_portal",
        "application_portal_url": "https://bkm.pollub.pl/en",
        "semester_fee_eur": 0,
        "notes": "Computer Science (EN): €2,000/semester = €4,000/yr. Source: bkm.pollub.pl/en/admission/studies-in-english/tuition-fees",
        "programs_list": [
            {"field_of_study": "Computer Science", "degree_level": "bachelor", "tuition_fee_eur": 4000, "notes": "€2,000/semester — verified from bkm.pollub.pl"},
            {"field_of_study": "AI & Business Solutions", "degree_level": "master", "tuition_fee_eur": 2600, "notes": "€1,300/semester — verified from bkm.pollub.pl"},
            {"field_of_study": "Civil Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU (Polish-taught)"},
            {"field_of_study": "Mechanical Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Engineering", "degree_level": "master", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Opole University of Technology",
        "country": "Poland",
        "city": "Opole",
        "website": "https://po.edu.pl/en",
        "description": "Public technical university in southwestern Poland offering civil engineering, mechanical engineering, electrical engineering, computer science, and economics.",
        "ranking": 701,
        "tuition_fee_eur": 2800,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Civil Engineering, Mechanical Engineering, Electrical Engineering, Computer Science, Economics",
        "application_method": "own_portal",
        "application_portal_url": "https://rekrutacja.po.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~2,800–3,500 EUR/yr. Source: po.edu.pl",
        "programs_list": [
            {"field_of_study": "Civil Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Mechanical Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Computer Science", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Engineering", "degree_level": "master", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Rzeszow University of Technology",
        "country": "Poland",
        "city": "Rzeszów",
        "website": "https://prz.edu.pl/en",
        "description": "Public technical university in southeastern Poland focusing on aviation, aerospace, mechanical engineering, civil engineering, and computer science. Known as the Aviation Valley university.",
        "ranking": 601,
        "tuition_fee_eur": 3500,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Aviation, Aerospace, Mechanical Engineering, Civil Engineering, Computer Science",
        "application_method": "own_portal",
        "application_portal_url": "https://rekrutacja.prz.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~3,000–4,000 EUR/yr. Source: prz.edu.pl",
        "programs_list": [
            {"field_of_study": "Aviation & Aerospace Engineering", "degree_level": "bachelor", "tuition_fee_eur": 4000, "notes": "~4,000 EUR/yr non-EU"},
            {"field_of_study": "Mechanical Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Civil Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Computer Science", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Engineering", "degree_level": "master", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "West Pomeranian University of Technology in Szczecin",
        "country": "Poland",
        "city": "Szczecin",
        "website": "https://zut.edu.pl/en",
        "description": "Large public technical university in northwestern Poland offering architecture, civil engineering, chemical technology, food sciences, biotechnology, and IT.",
        "ranking": 601,
        "tuition_fee_eur": 3500,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Architecture, Civil Engineering, Chemical Technology, Food Sciences, Biotechnology, IT",
        "application_method": "own_portal",
        "application_portal_url": "https://rekrutacja.zut.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~3,000–4,000 EUR/yr. Source: zut.edu.pl",
        "programs_list": [
            {"field_of_study": "Architecture", "degree_level": "bachelor", "tuition_fee_eur": 4000, "notes": "~4,000 EUR/yr non-EU"},
            {"field_of_study": "Civil & Environmental Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Chemical Technology & Biotechnology", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Food Sciences", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Engineering", "degree_level": "master", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Cracow University of Technology",
        "country": "Poland",
        "city": "Krakow",
        "website": "https://pk.edu.pl/en",
        "description": "Public technical university in Kraków offering architecture, civil engineering, mechanical engineering, chemical engineering, environmental engineering, and computer science.",
        "ranking": 401,
        "tuition_fee_eur": 4000,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Architecture, Civil Engineering, Mechanical Engineering, Chemical Engineering, Computer Science",
        "application_method": "own_portal",
        "application_portal_url": "https://iro.pk.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees verified from iro.pk.edu.pl/useful-hints/tuition-fees/ — Architecture EN: 5,000/yr, Civil Eng EN: 3,000/yr, Mechanical EN: 3,500/yr",
        "programs_list": [
            {"field_of_study": "Architecture", "degree_level": "bachelor", "tuition_fee_eur": 5000, "notes": "€5,000/yr — English program. Source: iro.pk.edu.pl"},
            {"field_of_study": "Civil Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "€3,000/yr — English program. Source: iro.pk.edu.pl"},
            {"field_of_study": "Mechanical Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "€3,500/yr — English program. Source: iro.pk.edu.pl"},
            {"field_of_study": "Chemical Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "€3,000/yr non-EU"},
            {"field_of_study": "Architecture", "degree_level": "master", "tuition_fee_eur": 5000, "notes": "€5,000/yr — English program"},
            {"field_of_study": "Civil Engineering", "degree_level": "master", "tuition_fee_eur": 3000, "notes": "€3,000/yr — English program"},
            {"field_of_study": "Computer Science & Applied Physics", "degree_level": "master", "tuition_fee_eur": 3000, "notes": "€3,000/yr — English program. Source: iro.pk.edu.pl"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },

    # ===== ECONOMIC UNIVERSITIES =====
    {
        "name": "University of Economics in Katowice",
        "country": "Poland",
        "city": "Katowice",
        "website": "https://www.ue.katowice.pl/en",
        "description": "Public economic university in Silesia offering economics, finance, management, informatics, and business analytics.",
        "ranking": 501,
        "tuition_fee_eur": 4500,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Economics, Finance, Management, Informatics, Business Analytics",
        "application_method": "irk",
        "application_portal_url": "https://irk.ue.katowice.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~4,000–5,500 EUR/yr. Source: ue.katowice.pl",
        "programs_list": [
            {"field_of_study": "Economics & Finance", "degree_level": "bachelor", "tuition_fee_eur": 4500, "notes": "~4,500 EUR/yr non-EU"},
            {"field_of_study": "Management & Business", "degree_level": "bachelor", "tuition_fee_eur": 4500, "notes": "~4,500 EUR/yr non-EU"},
            {"field_of_study": "Informatics & Business Analytics", "degree_level": "bachelor", "tuition_fee_eur": 4500, "notes": "~4,500 EUR/yr non-EU"},
            {"field_of_study": "Economics", "degree_level": "master", "tuition_fee_eur": 5000, "notes": "~5,000 EUR/yr non-EU"},
            {"field_of_study": "Management", "degree_level": "master", "tuition_fee_eur": 5000, "notes": "~5,000 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Krakow University of Economics",
        "country": "Poland",
        "city": "Krakow",
        "website": "https://uek.krakow.pl/en",
        "description": "Public economic university in Kraków offering economics, finance, management, commodity science, and applied computer science. One of the largest economic universities in Poland.",
        "ranking": 401,
        "tuition_fee_eur": 5000,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Economics, Finance, Management, Commodity Science, Applied Computer Science",
        "application_method": "irk",
        "application_portal_url": "https://irk.uek.krakow.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~4,500–5,500 EUR/yr. Source: uek.krakow.pl",
        "programs_list": [
            {"field_of_study": "Economics & Finance", "degree_level": "bachelor", "tuition_fee_eur": 5000, "notes": "~5,000 EUR/yr non-EU"},
            {"field_of_study": "Management & Business", "degree_level": "bachelor", "tuition_fee_eur": 5000, "notes": "~5,000 EUR/yr non-EU"},
            {"field_of_study": "Applied Computer Science", "degree_level": "bachelor", "tuition_fee_eur": 5000, "notes": "~5,000 EUR/yr non-EU"},
            {"field_of_study": "Economics", "degree_level": "master", "tuition_fee_eur": 5000, "notes": "~5,000 EUR/yr non-EU"},
            {"field_of_study": "Management", "degree_level": "master", "tuition_fee_eur": 5000, "notes": "~5,000 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Poznan University of Economics and Business",
        "country": "Poland",
        "city": "Poznan",
        "website": "https://ue.poznan.pl/en",
        "description": "Public economic university in Poznań offering economics, management, finance, international business, and data analytics.",
        "ranking": 401,
        "tuition_fee_eur": 4500,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Economics, Management, Finance, International Business, Data Analytics",
        "application_method": "irk",
        "application_portal_url": "https://irk.ue.poznan.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~4,000–5,000 EUR/yr. Source: ue.poznan.pl",
        "programs_list": [
            {"field_of_study": "Economics & Finance", "degree_level": "bachelor", "tuition_fee_eur": 4500, "notes": "~4,500 EUR/yr non-EU"},
            {"field_of_study": "International Business", "degree_level": "bachelor", "tuition_fee_eur": 4500, "notes": "~4,500 EUR/yr non-EU"},
            {"field_of_study": "Data Analytics", "degree_level": "bachelor", "tuition_fee_eur": 4500, "notes": "~4,500 EUR/yr non-EU"},
            {"field_of_study": "Economics", "degree_level": "master", "tuition_fee_eur": 4500, "notes": "~4,500 EUR/yr non-EU"},
            {"field_of_study": "Management", "degree_level": "master", "tuition_fee_eur": 4500, "notes": "~4,500 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Wroclaw University of Economics and Business",
        "country": "Poland",
        "city": "Wroclaw",
        "website": "https://ue.wroc.pl/en",
        "description": "Public economic university in Wrocław offering economics, management, finance, logistics, and computer science in economics.",
        "ranking": 401,
        "tuition_fee_eur": 4500,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Economics, Management, Finance, Logistics, Computer Science in Economics",
        "application_method": "irk",
        "application_portal_url": "https://irk.ue.wroc.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~4,000–5,000 EUR/yr. Source: ue.wroc.pl",
        "programs_list": [
            {"field_of_study": "Economics & Finance", "degree_level": "bachelor", "tuition_fee_eur": 4500, "notes": "~4,500 EUR/yr non-EU"},
            {"field_of_study": "Management & Logistics", "degree_level": "bachelor", "tuition_fee_eur": 4500, "notes": "~4,500 EUR/yr non-EU"},
            {"field_of_study": "Computer Science in Economics", "degree_level": "bachelor", "tuition_fee_eur": 4500, "notes": "~4,500 EUR/yr non-EU"},
            {"field_of_study": "Economics", "degree_level": "master", "tuition_fee_eur": 4500, "notes": "~4,500 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },

    # ===== AGRICULTURAL / LIFE SCIENCES =====
    {
        "name": "Warsaw University of Life Sciences",
        "country": "Poland",
        "city": "Warsaw",
        "website": "https://www.sggw.edu.pl/en",
        "description": "The largest agricultural university in Poland (SGGW). Offers agriculture, veterinary medicine, food technology, forestry, environmental management, and biotechnology.",
        "ranking": 401,
        "tuition_fee_eur": 4000,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Agriculture, Veterinary Medicine, Food Technology, Forestry, Biotechnology",
        "application_method": "irk",
        "application_portal_url": "https://irk.sggw.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~3,500–10,000 EUR/yr. Veterinary medicine significantly higher.",
        "programs_list": [
            {"field_of_study": "Agriculture & Agronomy", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Veterinary Medicine", "degree_level": "bachelor", "tuition_fee_eur": 9500, "notes": "~9,500 EUR/yr non-EU"},
            {"field_of_study": "Food Technology & Biotechnology", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Forestry & Environmental Management", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Agriculture", "degree_level": "master", "tuition_fee_eur": 4000, "notes": "~4,000 EUR/yr non-EU"},
            {"field_of_study": "Biotechnology", "degree_level": "master", "tuition_fee_eur": 4000, "notes": "~4,000 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Poznan University of Life Sciences",
        "country": "Poland",
        "city": "Poznan",
        "website": "https://www.up.poznan.pl/en",
        "description": "Public agricultural university in Poznań offering agronomy, veterinary medicine, food science, forestry, and environmental management.",
        "ranking": 401,
        "tuition_fee_eur": 4000,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Agronomy, Veterinary Medicine, Food Science, Forestry, Environmental Management",
        "application_method": "irk",
        "application_portal_url": "https://irk.up.poznan.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~3,500–9,000 EUR/yr. Veterinary significantly higher.",
        "programs_list": [
            {"field_of_study": "Agronomy & Agriculture", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Veterinary Medicine", "degree_level": "bachelor", "tuition_fee_eur": 9000, "notes": "~9,000 EUR/yr non-EU"},
            {"field_of_study": "Food Science", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Forestry", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Agronomy", "degree_level": "master", "tuition_fee_eur": 4000, "notes": "~4,000 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "University of Agriculture in Krakow",
        "country": "Poland",
        "city": "Krakow",
        "website": "https://en.urk.edu.pl",
        "description": "Public agricultural university in Kraków offering agriculture, forestry, food technology, environmental engineering, and biotechnology.",
        "ranking": 501,
        "tuition_fee_eur": 3500,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Agriculture, Forestry, Food Technology, Environmental Engineering, Biotechnology",
        "application_method": "irk",
        "application_portal_url": "https://irk.urk.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~3,000–4,000 EUR/yr. Source: urk.edu.pl",
        "programs_list": [
            {"field_of_study": "Agriculture & Agronomy", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Forestry", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Food Technology", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Environmental Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Agriculture", "degree_level": "master", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Wroclaw University of Environmental and Life Sciences",
        "country": "Poland",
        "city": "Wroclaw",
        "website": "https://upwr.edu.pl/en",
        "description": "Public agricultural and life sciences university in Wrocław offering agronomy, veterinary medicine, food sciences, environmental engineering, and biology.",
        "ranking": 401,
        "tuition_fee_eur": 4000,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Agronomy, Veterinary Medicine, Food Sciences, Environmental Engineering, Biology",
        "application_method": "irk",
        "application_portal_url": "https://irk.upwr.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~3,500–9,500 EUR/yr. Veterinary significantly higher.",
        "programs_list": [
            {"field_of_study": "Agronomy & Agriculture", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Veterinary Medicine", "degree_level": "bachelor", "tuition_fee_eur": 9500, "notes": "~9,500 EUR/yr non-EU"},
            {"field_of_study": "Food Sciences", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Environmental Engineering", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Biology", "degree_level": "bachelor", "tuition_fee_eur": 3500, "notes": "~3,500 EUR/yr non-EU"},
            {"field_of_study": "Agronomy", "degree_level": "master", "tuition_fee_eur": 4000, "notes": "~4,000 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },

    # ===== MEDICAL UNIVERSITIES =====
    {
        "name": "Medical University of Bialystok",
        "country": "Poland",
        "city": "Bialystok",
        "website": "https://www.umb.edu.pl/en",
        "description": "Public medical university in northeastern Poland offering medicine, dentistry, pharmacy, nursing, and medical biotechnology in English.",
        "ranking": 501,
        "tuition_fee_eur": 14000,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Medicine, Dentistry, Pharmacy, Nursing, Medical Biotechnology",
        "application_method": "own_portal",
        "application_portal_url": "https://www.umb.edu.pl/en/admission",
        "semester_fee_eur": 0,
        "notes": "Source: umb.edu.pl/en/admission/tuition_and_fees — Medicine ~14,000 EUR/yr, Dentistry ~15,000 EUR/yr",
        "programs_list": [
            {"field_of_study": "Medicine", "degree_level": "bachelor", "tuition_fee_eur": 14000, "notes": "~14,000 EUR/yr — Source: umb.edu.pl"},
            {"field_of_study": "Dentistry", "degree_level": "bachelor", "tuition_fee_eur": 15000, "notes": "~15,000 EUR/yr — Source: umb.edu.pl"},
            {"field_of_study": "Pharmacy", "degree_level": "bachelor", "tuition_fee_eur": 9000, "notes": "~9,000 EUR/yr — Source: umb.edu.pl"},
            {"field_of_study": "Nursing", "degree_level": "bachelor", "tuition_fee_eur": 6000, "notes": "~6,000 EUR/yr"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Medical University of Lublin",
        "country": "Poland",
        "city": "Lublin",
        "website": "https://umlub.edu.pl/en",
        "description": "Public medical university in eastern Poland offering medicine, dentistry, pharmacy, and public health in English. One of the largest medical universities in Poland.",
        "ranking": 401,
        "tuition_fee_eur": 14000,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Medicine, Dentistry, Pharmacy, Public Health, Nursing",
        "application_method": "own_portal",
        "application_portal_url": "https://umlub.edu.pl/en/admissions",
        "semester_fee_eur": 0,
        "notes": "Medicine ~14,000 EUR/yr for international students. Source: umlub.edu.pl",
        "programs_list": [
            {"field_of_study": "Medicine", "degree_level": "bachelor", "tuition_fee_eur": 14000, "notes": "~14,000 EUR/yr for international students"},
            {"field_of_study": "Dentistry (DDS)", "degree_level": "bachelor", "tuition_fee_eur": 15000, "notes": "~15,000 EUR/yr for international students"},
            {"field_of_study": "Pharmacy", "degree_level": "bachelor", "tuition_fee_eur": 9000, "notes": "~9,000 EUR/yr"},
            {"field_of_study": "Public Health & Nursing", "degree_level": "bachelor", "tuition_fee_eur": 6000, "notes": "~6,000 EUR/yr"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Medical University of Silesia in Katowice",
        "country": "Poland",
        "city": "Katowice",
        "website": "https://sum.edu.pl/en",
        "description": "Large public medical university in Katowice offering medicine, dentistry, pharmacy, and nursing with extensive English-language programs.",
        "ranking": 401,
        "tuition_fee_eur": 15360,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Medicine, Dentistry, Pharmacy, Nursing",
        "application_method": "own_portal",
        "application_portal_url": "https://admission.sum.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Source: admission.sum.edu.pl/tuition-fees — Medicine 65,500 PLN/yr ≈ €15,360, Dentistry 68,400 PLN/yr ≈ €16,020, Nursing BSc 42,200 PLN/yr ≈ €9,840 (2026/27 rates)",
        "programs_list": [
            {"field_of_study": "Medicine", "degree_level": "bachelor", "tuition_fee_eur": 15360, "notes": "65,500 PLN/yr ≈ €15,360 — Source: admission.sum.edu.pl"},
            {"field_of_study": "Dentistry", "degree_level": "bachelor", "tuition_fee_eur": 16020, "notes": "68,400 PLN/yr ≈ €16,020 — Source: admission.sum.edu.pl"},
            {"field_of_study": "Nursing (BSc)", "degree_level": "bachelor", "tuition_fee_eur": 9840, "notes": "42,200 PLN/yr ≈ €9,840 — Source: admission.sum.edu.pl"},
            {"field_of_study": "Nursing (MSc)", "degree_level": "master", "tuition_fee_eur": 3920, "notes": "16,800 PLN/yr ≈ €3,920 — Source: admission.sum.edu.pl"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Medical University of Lodz",
        "country": "Poland",
        "city": "Lodz",
        "website": "https://umed.lodz.pl/en",
        "description": "Public medical university in Łódź offering medicine, dentistry, pharmacy, health sciences, and nursing. One of the major Polish medical universities.",
        "ranking": 401,
        "tuition_fee_eur": 14000,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Medicine, Dentistry, Pharmacy, Nursing, Health Sciences",
        "application_method": "own_portal",
        "application_portal_url": "https://registration.umed.lodz.pl",
        "semester_fee_eur": 0,
        "notes": "Medicine ~14,000 EUR/yr for international students. Source: umed.lodz.pl",
        "programs_list": [
            {"field_of_study": "Medicine", "degree_level": "bachelor", "tuition_fee_eur": 14000, "notes": "~14,000 EUR/yr for international students"},
            {"field_of_study": "Dentistry", "degree_level": "bachelor", "tuition_fee_eur": 14000, "notes": "~14,000 EUR/yr for international students"},
            {"field_of_study": "Pharmacy", "degree_level": "bachelor", "tuition_fee_eur": 9000, "notes": "~9,000 EUR/yr"},
            {"field_of_study": "Nursing", "degree_level": "bachelor", "tuition_fee_eur": 6000, "notes": "~6,000 EUR/yr"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
    {
        "name": "Pomeranian Medical University in Szczecin",
        "country": "Poland",
        "city": "Szczecin",
        "website": "https://www.pum.edu.pl/en",
        "description": "Public medical university in northwestern Poland offering medicine, dentistry, pharmacy, nursing, and medical laboratory science in English.",
        "ranking": 501,
        "tuition_fee_eur": 14500,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Medicine, Dentistry, Pharmacy, Nursing, Medical Laboratory Science",
        "application_method": "own_portal",
        "application_portal_url": "https://apply.pum.edu.pl",
        "semester_fee_eur": 0,
        "notes": "Source: apply.pum.edu.pl/contents/content/62-fees — Medicine: 14,500 EUR/yr (years 1–3), 14,000 EUR/yr (years 4–5), 10,000 EUR (year 6)",
        "programs_list": [
            {"field_of_study": "Medicine", "degree_level": "bachelor", "tuition_fee_eur": 14500, "notes": "14,500 EUR/yr years 1–3, 14,000 EUR/yr years 4–5. Source: apply.pum.edu.pl"},
            {"field_of_study": "Dentistry", "degree_level": "bachelor", "tuition_fee_eur": 15000, "notes": "~15,000 EUR/yr — Source: pum.edu.pl"},
            {"field_of_study": "Pharmacy", "degree_level": "bachelor", "tuition_fee_eur": 9000, "notes": "~9,000 EUR/yr"},
            {"field_of_study": "Nursing", "degree_level": "bachelor", "tuition_fee_eur": 6000, "notes": "~6,000 EUR/yr"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },

    # ===== OTHER =====
    {
        "name": "Pedagogical University of Krakow",
        "country": "Poland",
        "city": "Krakow",
        "website": "https://up.krakow.pl/en",
        "description": "Public pedagogical and research university in Kraków offering education, humanities, social sciences, natural sciences, mathematics, and arts.",
        "ranking": 601,
        "tuition_fee_eur": 3000,
        "is_public": True,
        "english_programs_available": True,
        "programs": "Education, Humanities, Social Sciences, Natural Sciences, Mathematics, Arts",
        "application_method": "irk",
        "application_portal_url": "https://irk.up.krakow.pl",
        "semester_fee_eur": 0,
        "notes": "Fees for non-EU: ~2,800–3,500 EUR/yr. Source: up.krakow.pl",
        "programs_list": [
            {"field_of_study": "Education & Pedagogy", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Humanities & Social Sciences", "degree_level": "bachelor", "tuition_fee_eur": 2800, "notes": "~2,800 EUR/yr non-EU"},
            {"field_of_study": "Natural Sciences & Mathematics", "degree_level": "bachelor", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "Education", "degree_level": "master", "tuition_fee_eur": 3000, "notes": "~3,000 EUR/yr non-EU"},
            {"field_of_study": "All fields", "degree_level": "phd", "tuition_fee_eur": 0, "notes": "PhD free for admitted students"},
        ],
    },
]

added = 0
skipped = 0
for uni in UNIVERSITIES:
    if uni["name"] in existing:
        print(f"Skipped (exists): {uni['name']}")
        skipped += 1
        continue
    programs_list = uni.pop("programs_list", [])
    uid = insert_university(uni)
    insert_programs(uid, programs_list)
    print(f"Added (ID {uid}): {uni['name']}")
    added += 1

db.commit()
db.close()
print(f"\nDone: {added} added, {skipped} skipped.")
